export enum MutationType {
  SET_USER = "SET_USER",
  SET_TOKEN = "SET_TOKEN",
  SET_STOREID = "SET_STOREID",
  SET_ACCOUNT = "SET_ACCOUNT",
  SET_GENERAL = "SET_GENERAL",
  SET_PROFILE = "SET_PROFILE",
  SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE",
  RESET_STATE = "RESET_STATE_USER"
}
