export enum MutationType {
  SET_USER = "SET_USER",
  SET_TOKEN = "SET_TOKEN",
  SET_STOREID = "SET_STOREID",
  REMOVE_TOKEN = "REMOVE_TOKEN",
  REMOVE_STOREID = "REMOVE_STOREID",
  REMOVE_USER = "REMOVE_USER"
}
