image: node:latest

stages:
  - build
  - staging

cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  - apt-get update -qq && apt-get install

Build:
  stage: build
  tags:
    - gitlab-org-docker
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - npm run build

Deploy to Staging:
  stage: staging
  tags:
    - node
  before_script:
    # Generates to connect to the AWS unit the SSH key.
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    # Sets the permission to 600 to prevent a problem with AWS
    # that it's too unprotected.
    - chmod 600  ~/.ssh/id_rsa
  script:
    - echo "Deploy to production server"
  when: manual


