export enum ActionType {
  GET_CATEGORIES = "GET_CATEGORIES",
  CREATE_CATEGORY = "CREATE_CATEGORY",
  EDIT_CATEGORY = "EDIT_CATEGORY",
  DELETE_CATEGORY = "DELETE_CATEGORY",
  GET_CATEGORY_PRODUCTS = "GET_CATEGORY_PRODUCTS",
  ADD_PRODUCTS_TO_CATEGORY = "ADD_PRODUCTS_TO_CATEGORY",
  DELETE_PRODUCT_FROM_CATEGORY = "DELETE_PRODUCT_FROM_CATEGORY",
  DELETE_ALL_PRODUCTS_FROM_CATEGORY = "DELETE_ALL_PRODUCTS_FROM_CATEGORY"
}
