export enum RouteNames {
  MAIN_LAYOUT = "MAIN_LAYOUT",
  MAIN_PAGE = "MAIN_PAGE",
  PRODUCTS = "PRODUCTS",
  PROFILE = "PROFILE",
  SIGN_IN = "SIGN_IN",
  SIGN_UP = "SIGN_UP",
  CATEGORIES = "CATEGORIES",
  ORDERS = "ORDERS",
  BUYERS = "BUYERS",
  PRODUCT = "PRODUCT",
}
