export enum RouteNames {
  MAIN_LAYOUT = "MAIN_LAYOUT",
  MAIN_PAGE = "MAIN_PAGE",
  PRODUCTS = "PRODUCTS",
  PRODUCT = "PRODUCT",
  CREATE_PRODUCT = "CREATE_PRODUCT",
  PROFILE = "PROFILE",
  SIGN_IN = "SIGN_IN",
  SIGN_UP = "SIGN_UP",
  CATEGORIES = "CATEGORIES",
  ORDERS = "ORDERS",
  BUYERS = "BUYERS",
  CREATE_PRODUCTS = "CREATE_PRODUCTS",
  CUSTOMERS = "CUSTOMERS"
}
